### ISSUE TITLE
Firefox not supported?

### ISSUE THREAD

**Issue by vindberg** [circlecell/jsonlintpro#1]
There seem to be an issue with Firefox here using 18.0.1. See screenshot for the details. Thanks for an otherwise great "app".

![jsonlintpro_in_firefox](https://f.cloud.github.com/assets/225174/126670/24d5948e-6f6c-11e2-9d26-14d700382f92.png)

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
