### ISSUE TITLE
Be able to share the JSON page with data

### ISSUE THREAD

**Issue by tavuntu** [circlecell/jsonlintpro#11]
It would be nice to paste a JSON, parse it and then share a link to a guy in the team so he can see the same formatted JSON

**Comment by tavuntu** [comment]
Sorry, I just saw somebody else already asked for it.

**Comment by finom** [comment]
Yep. We're working under fantastic new version of jsonlint.com.
16 Июн 2016 г. 19:47 пользователь "tavuntu" <notifications@github.com>
написал:
