### ISSUE TITLE
[Feature Request] Fold

### ISSUE THREAD

**Issue by janosimas** [circlecell/jsonlintpro#12]
It would be great to be able to fold some objects.

here's an example: http://codebeautify.org/jsonvalidate

**Comment by finom** [comment]
Can you explain more detailed what does "fold" mean?

2016-06-17 15:56 GMT+03:00 Jano Simas <notifications@github.com>:

**Comment by janosimas** [comment]
I'm not sure how to explain,
if you get a json and paste validate in this site: http://codebeautify.org/jsonvalidate
you'll see some small triangles in the 'line numbers bar', clicking on them the editor hides that object from the code.

For long json objects it's a great feature.

**Comment by finom** [comment]
Got it.
17 Июн 2016 г. 18:42 пользователь "Jano Simas" <notifications@github.com>
написал:

**Comment by finom** [comment]
Done for jsonlint.com and jsoncompare.com
