### ISSUE TITLE
Long num changed after validation

### ISSUE THREAD

**Issue by hsqs** [circlecell/jsonlintpro#15]
{"i":[4012441203977093419,4012441203977093420],"a":2}   
when formating this json, the result number will be changed, like this:
{
    "i": [
        4012441203977093600,
        4012441203977093600
    ],
    "a": 2
}

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
