### ISSUE TITLE
Add ability to remove whitespace and compact the JSON

### ISSUE THREAD

**Issue by jwcobb** [circlecell/jsonlintpro#3]
Would love to see this added. http://jsonviewer.stack.hu/ supports it and it is very useful

**Comment by circlecell** [comment]
@finom thoughts?

**Comment by finom** [comment]
@circlecell we can add "minify" button.

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
