### ISSUE TITLE
floating point number precision issue causes output to have different values than input

### ISSUE THREAD

**Issue by borisdiakur** [circlecell/jsonlintpro#4]
Try this:

```
{
    "foobar": 99999999999999999
}
```

Click on the check button.

Expected output

```
{
    "foobar": 99999999999999999
}
```

Actual output:

```
{
    "foobar": 100000000000000000
}
```

**Comment by finom** [comment]
Thanks.

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
