### ISSUE TITLE
its awesomebut why u do not integrate codemirror in it?

### ISSUE THREAD

**Issue by maqboolkhan** [circlecell/jsonlintpro#7]
if u add `codemirror` or `ace` in its textarea then we will have nice syntax highlighted code with code folding and other features !

**Comment by finom** [comment]
@circlecell what do you think?

**Comment by circlecell** [comment]
@finom agree

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
