### ISSUE TITLE
Would be awesome to have byte size shown somewhere

### ISSUE THREAD

**Issue by irakliy81** [circlecell/jsonlintpro#8]
It would be great if there was a simple byte size counter integrated (with and w/o whitespaces) - similar to how http://bytesizematters.com/ does it.

**Comment by DaAwesomeP** [comment]
I didn't look at the source, but it seems that that site is simply doing a character count.

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com) which is based on community requirements. "pro" is no longer maintained and the repo is going to be closed.
